<h3>Turmas para UTFPR</h3>
<div class="section">
 <div class="container">
	<div class="row">
		<div id="turma_lista">
			<table  border="1" class="table">
			<caption>UTFPR</caption>
			<thead>  
				<th>Nome</th> 
				<th>Data criação</th> 
				<th>Status</th>	
				<th>Cadastrada por</th>
				<th>Ingressar</th>	
			</thead>
			<tbody>
			   <?php  foreach ($contents as $content) : ?>
			   <tr>
			   
				<td><?php echo $content['nome_turma'];?></td>
				<td><?php echo $content['data_criacao'];?></td>
				<td><?php echo $content['ativo'];?></td>
				<td><?php echo $content['nome_usuario']. " ".$content['foto'];?></td>
				<td>Clique para ingressar</td>
			   <tr>
			   <?php endforeach; ?>
			</table> 
		</div>
		
 </div>
 <?php var_dump($usuario);?>
<fieldset>
<legend>Adicionar Turma</legend> 
  <div class="row">
          <div class="col-md-12">
            <form role="form" method="post" action="turma/cadastro">
              
			  <input type="hidden" name="action" value="insert" />
			  
			  <div class="form-group has-error">
                <label class="control-label" for="nome_turma">Nome</label>
                <input class="form-control input-lg" id="nome_turma" placeholder="Nome " type="text">
              </div>
			  
              <button type="submit" class="btn btn-default" id="cadastrar_turma">Cadastrar</button>
			  
            </form>
          </div>
    </div>
 <fieldset>
</div>
</div>