<h3>Turmas para UTFPR</h3>
<div class="section">
 <div class="container">
	<div class="row">
		<div id="turma_lista">
			<table  border="1" class="table">
			<caption>UTFPR</caption>
			<thead>  
				<th>Nome</th> 
				<th>Data criação</th> 
				<th>Status</th>	
				<th>Cadastrada por</th>
				<th>Ingressar</th>	
			</thead>
			<tbody>
			   <?php  foreach ($contents as $content) : ?>
			   <tr>
			   
				<td><?php echo $content['nome_turma'];?></td>
				<td><?php echo $content['data_criacao'];?></td>
				<td><?php echo $content['ativo'];?></td>
				<td><?php echo $content['nome_usuario']. " ".$content['foto'];?></td>
				<td>
					<?php if($content['id_usuario'] != $usuario_session->id){
						?>
						<button type="submit" class="btn btn-default" onClick="ingressar(<?php echo $usuario_session->id;?>, <?php echo $content['id_turma'];?>)" id="ingressar_turma">Ingressar</button>
					<?php
					}else{
						echo "Turma cadastrada por voce";
						?>
						<a href="<?php echo $this->url('turma-excluir', array(
																			'action' => 'excluir', 'id' => $content['id_turma']
									)); ?>">
                  			Excluir
						</a>
				</td>
					<?php	}?>
				</tr>
			   <tr>
			   <?php endforeach; ?>
			</table> 
		</div>
		
 </div>
 <?php echo $usuario_turma[0]['instituicao'];?>
<fieldset>
<legend>Adicionar Turma</legend> 
  <div class="row">
          <div class="col-md-12">
            <form role="form" method="post" action="<?php echo $this->url('turma-cadastro');?>">
              
			  <input type="hidden" name="action" value="insert" />
			  <input type="hidden" name="id_usuario" value="<?php echo $usuario_session->id;?>"/>
			  <input type="hidden" name="id_instituicao" value="<?php echo $usuario_turma[0]['instituicao'];?>"/>
			  <div class="form-group has-error">
                <label class="control-label" for="nome_turma">Nome</label>
                <input class="form-control input-lg" id="nome_turma" name="nome_turma" placeholder="Nome " type="text">
              </div>
			  
              <button type="submit" class="btn btn-default" id="cadastrar_turma">Cadastrar</button>
			  
            </form>
          </div>
    </div>
 <fieldset>
 
</div>
</div>
<script>
	function ingressar(id_usuario, id_turma){
		$.post('<?php echo $this->url('turma-ingressar');?>',
			{id_usuario:id_usuario, id_turma: id_turma},
			function(data){
				console.log('enviou usuario ' + id_usuario +' turma '+ id_turma);
			}
		);
	}
</script>