<?php
    $this->headTitle()->prepend($turma);
    echo $this->headTitle();
?>
     <!--Estilo da pagina, transferir para arquivo externo-->
     <style>
        #cadastrar_post { padding: .5em 1em; text-decoration: none; position: absolute; top:10%; }
        #ingressar_turma { padding: .5em 1em; text-decoration: none; position: absolute; top:10%; margin-left: 120px}
        #cadastro h3 { margin: 0; padding: 0.4em; text-align: center; }
        article header button{margin: 10px}
        article header span{margin: 10px}
        article{border: 1px solid; margin: 5px;}
    </style>

    <!--Verifica se usuario ja esta ingressado , se sim liberar btn postar.-->
    <?php if(isset($ingressar) && isset($usuario_session->id)){?>
        <button id="cadastrar_post" class="ui-state-default ui-corner-all">Postar</button>
    <?php }?>
    <?php if(!isset($ingressar) && isset($usuario_session->id)){?>
        <button id="ingressar_turma" class="ui-state-default ui-corner-all" onClick="ingressar(<?php echo $usuario_session->id;?>, <?php echo $id_turma;?>)">Ingressar</button>
    <?php }?>

    <div id="post">
     <?php  foreach ($post as $pst) : ?>
         <article>
             <header>

                 <h1 id="titulo<?php echo $pst['id_post'];?>"><?php echo $pst['titulo'];?></h1>

                 <?php echo "<span> postado por ". $pst['nome']." em ".$pst['data_post']."</span>";?>
                 <input type="hidden" name="id_post" value="<?php echo $pst['id_post'];?>" id="id_post">

                 <?php if($usuario_session->id == $pst['id_usuario']){?>

                    <button data-post_id="<?php echo $pst['id_post']; ?>" class="ui-state-default ui-corner-all post_id">
                        Editar
                    </button>
                    <button id="exluir_post<?php echo $pst['id_post'];?>" class="bnt btn-danger"
                            onClick="excluir_post(<?php echo $pst['id_post'];?>)">
                        Excluir
                    </button>
                 <?php }?>


             </header>
             <p id="conteudo<?php echo $pst['id_post'];?>"">
                 <?php echo  $pst['conteudo'];?>
             </p>
         </article>
     <?php endforeach; ?>
   </div>
     <script>
         $(function() {
             function runEffect() {
                 var selectedEffect = "drop";
                 var options = {};
                 $( "#cadastro" ).show( selectedEffect, options);
             };

             function callback() {
                 setTimeout(function() {
                     $( "#cadastro:visible" ).removeAttr( "style" ).fadeOut();
                 }, 1000 );
             };

             // set effect from select menu value
             $( "#cadastrar_post" ).click(function() {
                 runEffect();
             });

             $( "#cadastro" ).hide();

         });

         function excluir_post(id_post){
             $(function() {
                 $( "#dialog-confirm" ).dialog({
                     resizable: false,
                     height:140,
                     modal: true,
                     buttons: {
                         "Exluir post": function() {
                             $.post('<?php echo $this->url('post-excluir');?>',
                                 {id_post:id_post},
                                 function(data){
                                     ///window.location.href = '/conecta/public/usuario';
                                 }
                             );
                             $( this ).dialog( "close" );
                             window.setTimeout('location.reload()', 1000);
                         },
                         Cancelar: function() {
                             $( this ).dialog( "close" );
                         }
                     }
                 });
             });
             //window.setTimeout('location.reload()', 1000);
         }



         $(function() {
             var dialog, form, id_post,
                 titulo = $( "#titulo" ),
                 assunto = $( "#assunto" ),
                 allFields = $( [] ).add( titulo ).add( assunto ),
                 tips = $( ".validateTips" );

             function updateTips( t ) {
                 tips
                     .text( t )
                     .addClass( "ui-state-highlight" );
                 setTimeout(function() {
                     tips.removeClass( "ui-state-highlight", 1500 );
                 }, 500 );
             }

             function checkLength( o, n, min, max ) {
                 if ( o.val().length > max || o.val().length < min ) {
                     o.addClass( "ui-state-error" );
                     updateTips( "Para " + n + " insira no minio  " +
                         min + " e no maximo " + max + "." );
                     return false;
                 } else {
                     return true;
                 }
             }

             function checkRegexp( o, regexp, n ) {
                 if ( !( regexp.test( o.val() ) ) ) {
                     o.addClass( "ui-state-error" );
                     updateTips( n );
                     return false;
                 } else {
                     return true;
                 }
             }

             function addPost() {
                 var valid = true;
                 allFields.removeClass( "ui-state-error" );

                 valid = valid && checkLength( titulo, "titulo", 3, 40 );
                 valid = valid && checkLength( assunto, "assunto", 6, 1200 );

                 valid = valid && checkRegexp( titulo, /^[a-z]([0-9a-z_\s])+$/i, "Não é permitido caracterer especial." );
                 valid = valid && checkRegexp( assunto, /^[a-z]([0-9a-z_\s])+$/i, "Não é permitido caracterer especial." );


                 if ( valid ) {
                     $.post('<?php echo $this->url('post-cadastrar');?>',
                         {id_turma: $( "#id_turma" ).val(), id_usuario:$( "#id_usuario" ).val(), assunto:assunto.val(), titulo:titulo.val(),},
                         function(data){
                         }
                     );
                    dialog.dialog( "close" );
                    window.setTimeout('location.reload()', 1000);
                 }
                 return valid;
             }

             function editarPost(){
                 var valid = true;
                 allFields.removeClass( "ui-state-error" );

                 valid = valid && checkLength( titulo, "titulo", 3, 40 );
                 valid = valid && checkLength( assunto, "assunto", 6, 6000 );

                 valid = valid && checkRegexp( titulo, /^[a-z]([0-9a-z_\s])+$/i, "Não é permitido caracter especial." );
                 valid = valid && checkRegexp( assunto, /^[a-z]([0-9a-z_\s])+$/i, "Não é permitido caracter especial." );


                 if ( valid ) {
                     $.post('<?php echo $this->url('post-editar');?>',
                         {id_post:id_post, id_turma: $( "#id_turma" ).val(), id_usuario:$( "#id_usuario" ).val(), assunto:assunto.val(), titulo:titulo.val(),},
                         function(data){
                         }
                     );
                     dialog.dialog( "close" );
                     window.setTimeout('location.reload()', 1000);
                 }
                 return valid;
             }


             $(document).on('click', '.post_id', function() {

                 id_post = $(this).data('post_id');
                 var edit_titulo = $("#titulo" + id_post).text().trim();
                 var edit_assunto = $("#conteudo" + id_post).text().trim();

                 titulo.val(edit_titulo);
                 assunto.val(edit_assunto);


                 dialog = $("#dialog-form-post").dialog({
                     autoOpen: false,
                     height: 300,
                     width: 450,
                     modal: true,
                     buttons: {
                         "Editar post": editarPost,
                         Cancelar: function () {
                             dialog.dialog("close");
                         }
                     },
                     close: function () {
                         form[0].reset();
                         allFields.removeClass("ui-state-error");
                     }
                 });
                 dialog.dialog("open");
             });

             dialog = $( "#dialog-form-post" ).dialog({
                 autoOpen: false,
                 height: 300,
                 width: 450,
                 modal: true,
                 buttons: {
                     "Adiconar post": addPost,
                     Cancelar: function() {
                         dialog.dialog( "close" );
                     }
                 },
                 close: function() {
                     form[ 0 ].reset();
                     allFields.removeClass( "ui-state-error" );
                 }
             });

             form = dialog.find( "form" ).on( "submit", function( event ) {
                 event.preventDefault();
             });

             $( "#cadastrar_post" ).button().on( "click", function() {
                 dialog.dialog( "open" );
             });


         });

   </script>

   <!--Mensagem de confirmacao de exclusao de post -->
   <div id="dialog-confirm" title="Gostaria de excluir o post?">
      <p><span class="ui-icon ui-icon-alert"></span></p>
   </div>

     <!--Modal para cadastro -->
     <div id="dialog-form-post" title="Adicionar post">
         <p class="validateTips">Titulo e assunto requeridos.</p>

         <form>
             <fieldset>
                 <input type="hidden" value="<?php echo $usuario_session->id;?>" name="id_usuario" id="id_usuario">
                 <input type="hidden" value="<?php echo $id_turma;?>" name="id_turma" id="id_turma">
                 <label for="titulo">Titulo</label>
                 <input type="text" name="titulo" id="titulo" class="text ui-widget-content ui-corner-all">
                  <br>
                 <label for="assunto">Assunto</label>
                 <textarea rows="3" cols="43" id="assunto" name="assunto"></textarea>
                  <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
             </fieldset>
         </form>
     </div>
     <script>
         function ingressar(id_usuario, id_turma){
             $.post('<?php echo $this->url('turma-ingressar');?>',
                 {id_usuario:id_usuario, id_turma: id_turma},
                 function(data){
                     ///window.location.href = '/conecta/public/usuario';
                 }
             );
             //window.location.href = '/conecta/public/usuario/index';
         }
     </script>