<?php
    $this->headTitle()->prepend('Comentarios para '.$turma);
    echo $this->headTitle();

?>

     <!--Estilo da pagina, transferir para arquivo externo-->
     <style>
        #cadastrar_comentario { padding: .5em 1em; text-decoration: none; position: absolute; top:10%; }
        #ingressar_turma { padding: .5em 1em; text-decoration: none; position: absolute; top:10%; margin-left: 120px}
        #cadastro h3 { margin: 0; padding: 0.4em; text-align: center; }
        #comentario{list-style: none;}
        article header button{margin: 10px}
        article header span{margin: 10px}
        article{border: 1px solid; margin: 5px;}
        .autor_comentario{font-size: 12px;}
        .conteudo_comentario{font-style: normal; font-weight: normal;}

    </style>

    <!--Verifica se usuario ja esta ingressado , se sim liberar btn postar.-->
    <?php if(isset($ingressar) && isset($usuario_session->id)){?>
        <button id="cadastrar_comentario" class="ui-state-default ui-corner-all"></button>
    <?php }?>

    <div id="comentario">
     <?php  foreach ($conteudoPost as $conteudo) : ?>
         <article>
             <header>
                 <h1><?php echo $conteudo['titulo'];?></h1>
                 <?php echo "<span> postado por ". $conteudo['nome']." em ".$conteudo['data_post']."</span>";?>
             </header>
             <p>
                 <?php echo  $conteudo['conteudo'];?>
             </p>
         </article>
     <?php endforeach; ?>
   </div>
<!--comentarios-->
<div id="comentarios">
     <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    <?php if(isset($conteudoPost[0]['id_usuario'])){?>
                        <button id="comentar" class="ui-state-default ui-corner-all">Comentar</button>
                    <?php }?>
                </th>
            </tr>
        </thead>
        <tbody>
        <tr>
         <?php  foreach ($comentarios as $comentario) : ?>
            <tr>
             <th scope="row">
                <ul class="list-group">
                    <li id="comentario<?php echo $comentario['id_comentario'];?>" class="conteudo_comentario list-group-item">
                        <?php echo $comentario['conteudo'];?>
                    </li>
                    <li class="autor_comentario list-group-item">
                        <?php echo "Realizado por ".$comentario['autor']." em ".$comentario['data_comentario'];?>


                    <input type="hidden" name="id_comentario" value="<?php echo $comentario['id_comentario'];?>" id="id_comentario">

                    <?php if($usuario_session->id == $comentario['id_usuario']):?>


                            <button data-comentario_id="<?php echo $comentario['id_comentario']; ?>" class="ui-state-default ui-corner-all comentario_id">
                                Editar
                            </button>

                            <button id="exluir_comentario<?php echo $comentario['id_comentario'];?>" class="bnt btn-danger"
                                    onClick="excluir_comentario(<?php echo $comentario['id_comentario'];?>,<?php echo $comentario['id_usuario'];?>)">
                                Excluir
                            </button>
                    </li>
                    <?php endif; ?>

                </ul>
            </th>
            </tr>
         <?php endforeach; ?>
        </tr>

    </tbody>
    </table>
    </div>
     <script>
         $(function() {
             function runEffect() {
                 var selectedEffect = "drop";
                 var options = {};
                 $( "#cadastro" ).show( selectedEffect, options);
             };

             function callback() {
                 setTimeout(function() {
                     $( "#cadastro:visible" ).removeAttr( "style" ).fadeOut();
                 }, 1000 );
             };

             // set effect from select menu value
             $( "#cadastrar_comentario" ).click(function() {
                 runEffect();
             });

             $( "#cadastro" ).hide();

         });

         function excluir_comentario(id_comentario,id_usuario){
             $(function() {
                 $( "#dialog-confirm" ).dialog({
                     resizable: false,
                     height:140,
                     modal: true,
                     buttons: {
                         "Exluir post": function() {
                             $.post('<?php echo $this->url('comentario-excluir');?>',
                                 {id_comentario:id_comentario, id_usuario:id_usuario},
                                 function(data){
                                 }
                             );
                             $( this ).dialog( "close" );
                            window.setTimeout('location.reload()', 100);
                         },
                         Cancelar: function() {
                             $( this ).dialog( "close" );
                         }
                     }
                 });
             });
            // window.setTimeout('location.reload()', 1000);
         }



         $(function() {
             var dialog, form, id_post,
                 comentario = $( "#conteudo_comentario" ),
                 allFields = $( [] ).add( comentario ),
                 tips = $( ".validateTips" );

             function updateTips( t ) {
                 tips
                     .text( t )
                     .addClass( "ui-state-highlight" );
                 setTimeout(function() {
                     tips.removeClass( "ui-state-highlight", 1500 );
                 }, 500 );
             }

             function checkLength( o, n, min, max ) {
                 if ( o.val().length > max || o.val().length < min ) {
                     o.addClass( "ui-state-error" );
                     updateTips( "Para " + n + " insira no minio  " +
                         min + " e no maximo " + max + "." );
                     return false;
                 } else {
                     return true;
                 }
             }

             function checkRegexp( o, regexp, n ) {
                 if ( !( regexp.test( o.val() ) ) ) {
                     o.addClass( "ui-state-error" );
                     updateTips( n );
                     return false;
                 } else {
                     return true;
                 }
             }

             function addPost() {
                 var valid = true;
                 allFields.removeClass( "ui-state-error" );

                 valid = valid && checkLength( comentario, "comentario", 3, 100);
                 valid = valid && checkRegexp( comentario, /^[a-z]([0-9a-z_.,\s])+$/i, "Não é permitido caracterer especial." );

                 if ( valid ) {
                         $.post('<?php echo $this->url('comentario-cadastrar');?>',
                         {id_post: $( "#id_post" ).val(), id_usuario:$( "#id_usuario" ).val(), conteudo_comentario:comentario.val(),},
                         function(data){
                         }
                     );
                    dialog.dialog( "close" );
                    window.setTimeout('location.reload()', 1000);
                 }
                 return valid;
             }

             function editarComentario(){
                 var valid = true;
                 allFields.removeClass( "ui-state-error" );

                 valid = valid && checkLength( comentario, "comentario", 3, 100);
                 valid = valid && checkRegexp( comentario, /^[a-z]([0-9a-z_.,\s])+$/i, "Não é permitido caracterer especial." );

                 if ( valid ) {
                     $.post('<?php echo $this->url('comentario-editar');?>',
                         {id_comentario: comentario_id, id_usuario:$( "#id_usuario" ).val(), conteudo_comentario:comentario.val(),},
                         function(data){
                         }
                     );
                     dialog.dialog( "close" );
                        window.setTimeout('location.reload()', 1);
                 }
                 return valid;
             }


             $(document).on('click', '.comentario_id', function() {
                 comentario_id = $(this).data('comentario_id');
                 var edit_comentario = $("#comentario" + comentario_id).text().trim();
                 comentario.val(edit_comentario);
                 dialog = $("#dialog-form-comentario").dialog({
                     autoOpen: false,
                     height: 300,
                     width: 450,
                     modal: true,
                     buttons: {
                         "Editar comentario": editarComentario,
                         Cancelar: function () {
                             dialog.dialog("close");
                         }
                     },
                     close: function () {
                         form[0].reset();
                         allFields.removeClass("ui-state-error");
                     }
                 });
                 dialog.dialog("open");
             });

             dialog = $( "#dialog-form-comentario" ).dialog({
                 autoOpen: false,
                 height: 300,
                 width: 450,
                 modal: true,
                 buttons: {
                     "Adicionar comentario": addPost,
                     Cancelar: function() {
                         dialog.dialog( "close" );
                     }
                 },
                 close: function() {
                     form[ 0 ].reset();
                     allFields.removeClass( "ui-state-error" );
                 }
             });

             form = dialog.find( "form" ).on( "submit", function( event ) {
                 event.preventDefault();
             });

             $( "#comentar" ).button().on( "click", function() {
                 dialog.dialog( "open" );
             });


         });

   </script>

   <!--Mensagem de confirmacao de exclusao de post -->
   <div id="dialog-confirm" title="Gostaria de excluir o comentario?">
   </div>

     <!--Modal para cadastro -->
     <div id="dialog-form-comentario" title="Adicionar comentario">
         <p class="validateTips">comentario</p>

         <form>
             <fieldset>
                 <input type="hidden" value="<?php echo $usuario_session->id;?>" name="id_usuario" id="id_usuario">
                 <input type="hidden" value="<?php echo $id_post;?>" name="id_post" id="id_post">
                 <label for="conteudo_comentario">Deixe seu comentario...</label>
                 <textarea rows="3" cols="43" id="conteudo_comentario" name="conteudo_comentario"></textarea>
                  <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
             </fieldset>
         </form>
     </div>
     <script>
         function ingressar(id_usuario, id_turma){
             $.post('<?php echo $this->url('turma-ingressar');?>',
                 {id_usuario:id_usuario, id_turma: id_turma},
                 function(data){
                     ///window.location.href = '/conecta/public/usuario';
                 }
             );
             //window.location.href = '/conecta/public/usuario/index';
         }
     </script>