
   <p>Logar 
		<button type="button" id="bt-facebook">Facebook</button>
	</p>
   <div class="bs-docs-example">
	   <div class="dropdown clearfix">
		   <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu" style="display: block; position: static; margin-bottom: 5px; *width: 180px;">
			   <li><strong>Turmas que voce segue</strong></li>
			   <li class="divider"></li>
			   <li><a tabindex="-1" href="#">ASD2016o</a></li>
			   <li class="divider"></li>
			   <li><a tabindex="-1" href="#">ANALISE2016</a></li>
			   <li class="divider"></li>

		   </ul>
	   </div>
   </div>