<h2>Turmas que você segue atualmente</h2>
   <div class="card-columns">
	   <?php  foreach ($turma as $tm) : ?>
	   <!--<a  tabindex="-1" href="<?php echo $this->url('turma-post', array('nome' => $tm['nome'] )); ?>">-->
		   <div class="card card-block text-xs-center">
			   <h4 class="card-title"><?php echo $tm['nome'];?></h4>
			   <p class="card-text">Voce esta seguindo esta turma, compartilhe seu conhecimento.</p>
			   <p><span class="badge"> <?php echo "Existem cerca de ". $tm['n_post']." assunto(s)s até o momento.";?></span></p>
			   <a href="<?php echo $this->url('turma-post', array('nome' => $tm['nome'] ));?>" class="btn btn-primary">Acompanhe...</a>
		   </div>
	   <!--</a>-->
	   <?php endforeach; ?>
	</div>

