<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Bem vindo ao Conecta'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Este aplicativo esta em desenvolvimento.'), '<a href="#"></a>')?></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Conecta') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Utilize suas rede socias para se conectar a sua faculdade.')) ?></p>
                <p><a class="btn btn-success pull-right" id="bt-facebook"><?php echo $this->translate('Utilize seu Facebook') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Turma') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Donec eu nisl ut nulla aliquam sollicitudin. Aliquam rutrum lorem sit amet nulla commodo, id cursus tortor commodo. Cras a sollicitudin turpis. Fusce convallis lectus in erat laoreet rutrum. Mauris varius, ipsum eget dictum pellentesque, tellus enim lacinia nisl, a gravida augue purus nec ex. Cras hendrerit lobortis mollis. Pellentesque quis erat ornare, viverra erat eget, venenatis libero. Nulla blandit nulla viverra, bibendum metus sit amet, auctor risus. Pellentesque sodales neque tellus, in porttitor sapien scelerisque ac. Fusce accumsan et massa efficitur consectetur. Aliquam accumsan nibh sed enim tincidunt, vitae ornare lectus molestie')) ?></p>
                <p><a class="btn btn-success pull-right"><?php echo $this->translate('Suas turmas') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Conteudo') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Pellentesque rutrum bibendum nibh sed lobortis. Vestibulum sapien ex, suscipit ut mauris at, pellentesque molestie risus. Donec id tellus a nunc feugiat lacinia. Vivamus et convallis leo. Fusce placerat arcu sed tempus imperdiet. Nunc eget orci ante. Mauris et blandit sapien. Maecenas pharetra purus sed dui cursus, sed consequat purus porttitor. In sit amet nisi porta, feugiat lacus ac, gravida ligula. Nam eleifend ex sit amet arcu pellentesque, sit amet commodo magna pellentesque. Quisque ipsum augue, commodo ut bibendum quis, commodo eu orci. Nullam consectetur, urna quis dignissim eleifend, nulla sem tempor quam, vel varius lacus orci id diam. Morbi euismod aliquet lorem ut pharetr'), '<a href="irc://irc.freenode.net/zftalk">') ?></p>
                <p><a class="btn btn-success pull-right"><?php echo $this->translate('O que estão conpartilhando') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
<script>

    var nome;
    var id;
    var foto;
    var faculdade;

    window.fbAsyncInit = function() {
        FB.init({
            appId      : '1712482102324462',
            xfbml      : true,
            version    : 'v2.6'
        });
    };

    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    //salvar dados em base

    function salvarDados(id, nome, faculdade){
        $.post('<?php echo $this->url('usuario-cadastro');?>',
            {id_usuario:id, nome: nome, faculdade: 1},
            function(data) {
                $(location).attr('href', '<?php echo $this->url('usuario');?>');
                //windown.location = '<?php //echo $this->url('usuario');?>';
            });
    }

    $('#bt-facebook').click( function(event){

        event.preventDefault();
        destino = this.href;

        FB.login( function(response){
            if (response.authResponse) {
                document.cookie = '1712482102324462='+response.authResponse.userID;
                document.cookie = 'ab478477ff68d9d2b7ad79298ffc586e='+response.authResponse.accessToken;
                FB.api('/me',
                    {fields: "id,about,age_range,picture,bio,birthday,context,email,first_name,gender,hometown,link,location,middle_name,name,timezone,website,work"},
                    function(response) {
                        console.log(response.id);
                        salvarDados(response.id, response.name, response.hometown);
                    }
                );
            }else{
                alert('NAO LOGOU');
                FB.login();
                // console.log('O usuário Cancelou o login ou não autozirou.');
            }
        }, {scope: 'user_photos, publish_actions, user_education_history, email'});
    });

</script>
